(function(){function ua(a){function e(a){function w(){e.onreadystatechange=e.onload=null;a.callback&&a.callback.apply(a)}var e=document.createElement("script");"undefined"!=typeof a.id&&(e.id=a.id);e.setAttribute("type","text/javascript");e.setAttribute("src",a.url);e.setAttribute("charset","utf-8");document.getElementsByTagName("head")[0].appendChild(e);e.onreadystatechange=function(){"loaded"!=this.readyState&&"complete"!=this.readyState||w()};e.onload=e.onerror=w}function f(){for(g.zid=g.zid||
"";g.funList[0];){var a=g.funList.shift();a&&a(g.zid)}}var g=window.__zpCMSDCB;g||(g=window.__zpCMSDCB=function(a){g.zid||g.bw||(g.bw=g.zid=g.zid||g.bw||a&&a.data||"")});g.funList=g.cE=g.funList||g.cE||[];g.bw=g.zid=g.zid||g.bw||a.zid;g.funList.push(a.fun);(g.isGet||g.ds||g.zid)&&f();g.zid||g.isTouch||g.dj||(g.isTouch=1,g.dj=1,e({url:H("//cms.gtags.net/g?z=__zpCMSDCB")+"&a="+a.a,callback:function(){g.isGet=1;g.ds=1;f()}}))}function W(){var a=navigator.userAgent||"";return-1<a.indexOf("MSIE 8.0")||
-1<a.indexOf("MSIE 7.0")||-1<a.indexOf("MSIE 6.0")?!0:!1}function la(a){for(var e in a)return!1;return!0}var M=navigator.userAgent.toLowerCase()||"";if(-1<M.indexOf("spider")||-1<M.indexOf("msnbot")||-1<M.indexOf("networkbench"))return!1;var t=document,p=window,ma=navigator,R=Image,N=Array,k=encodeURIComponent,a=decodeURIComponent,X="",I="",Y="",na,Z=0,oa=function(w){w=k(w)+"=";var e=t.cookie.indexOf(w),f="";-1<e&&(f=t.cookie.indexOf(";",e),-1==f&&(f=t.cookie.length),f=a(t.cookie.substring(e+w.length,
f)));return f},S=function(a){var e={};if(0<a.indexOf("?")){a=a.substring(a.indexOf("?")+1);0<a.indexOf("#")&&(a=a.substring(0,a.indexOf("#")));a=a.split("&");for(var f=0;f<a.length;f++)e[a[f].split("=")[0]]=a[f].split("=")[1]}if(void 0==e.zpclkid||""==e.zpclkid)e.zpclkid=window.__zpclkid;return e},aa=function(a,e,f){a.addEventListener?a.addEventListener(e,f,!1):a.attachEvent?a.attachEvent("on"+e,f):a["on"+e]=f},H=function(a){var e="";try{e="https:"==t.location.protocol?"https:":"http:"}catch(f){}return e+
a},pa=function(){var a=p.location.href;return a&&""!=a?a.replace(/\s/g," "):""},ba=function(){var a="";try{a=t.referrer}catch(e){}if(""==a)try{opener&&opener.location&&(a=opener.location.href)}catch(e){}return a&&""!=a?a.replace(/\s/g," "):a},va=function(a){return a?a:(a=pa().match(/[\w-]+\.(com|net|org|gov|cc|biz|info|cn|cc|tv|hk|biz|asia|me|mobi|name|info|so|co|in|la)(\.(cn|hk))*/))&&0<a.length?a[0]:null},m=function(a){a&&(a=a.replace(/[\s#,|]/g," "));return a},G=function(a){a&&"string"==typeof a&&
(a=a.replace(/^(\s|\u00A0)+/,"").replace(/(\s|\u00A0)+$/,""));return a},D=[["m.baidu","word"],["wap.baidu","word"],["opendata.baidu","wd"],["baidu","word"],["baidu","wd"],["baidu","q1"],["baidu","kw"],["google","q"],["soso","w"],["sogou","query"],["youdao","q"],["bing","q"],["yahoo","p"],["so.360.cn","q"],["360so","q"],["360sou","q"],["so.com","q"],["ask","q"],["3721","name"],["vent","kw"],["ucweb","keyword"],["ucweb","word"],["114so","kw"],["haosou","q"],["chinaso","q"],["zhongsou","w"],["etao.com",
"q"],[".sm.cn","q"]],ca=function(a){var e=/^https?:\/\/(.*?)($|\/.*)/.exec(a);if(null!=e){var f="",f=e[1];a=S(a);for(e=0;e<D.length;e++)if(0<=f.indexOf(D[e][0])&&"undefined"!=typeof a[D[e][1]])return[2,m(f),"","",m(a[D[e][1]]),""];return[3,m(f),"","","",""]}return[3,m(a),"","","",""]};(new function(){function w(a,c){var b="rid="+c+"&zid="+I;a=0<=a.indexOf("?")?a+("&"+b):a+("?"+b);var d=document.createElement("iframe");d.setAttribute("scrolling","no");d.frameBorder="0";d.src=a;d.style.cssText="width:1px;height:1px;position:fixed;_position:absolute;left:0px;top:0px;margin:0px;padding:0px;z-index:2147483648";
setTimeout(function(){try{document.body&&document.body.insertBefore(d,document.body.firstChild)}catch(b){setTimeout(arguments.callee,13)}},13);setTimeout(function(){try{d.parentNode.removeChild(d)}catch(b){}},1E4)}var e=!1,f=!1,g=null,L=0,V=0,Q=0,K=0,h=4,q="",E="",n="",F="",z="",T=0,M=0,A="",u="",J="",v="w",B=function(a){return a instanceof N&&2==a.length?a[1]:""},r="",da=va(),O="",l="",P="",ea="",d="",fa="",U={},qa={_addOrganic:function(a){a instanceof N&&3==a.length&&D.push([a[1],a[2]])},_setAccount:function(a){Y=
r=B(a)},_setDomain:function(a){da=B(a)},_setPageID:function(a){l=B(a)},_setPageType:function(a){P=B(a)},_setParams:function(a){if(a instanceof N){var c=a.length;16<c&&(c=16);for(var b=1,e=[];b<c;)e.push(k(G(a[b]))),b++;d=e.join(",")}},_setUserID:function(a){O=B(a)},_setMType:function(a){a instanceof N&&2==a.length&&("p"==a[1]?v="p":""==a[1]&&(v=""))},_setSiteID:function(a){ea=B(a)}},C="",ga="",ha="",ia="",ja="",aa=function(){if(""!=v&&!p.__zp_smartpixel_list[v+"_"+r]){var a=H("//cms.gtags.net/"+v)+
"?a="+r,a=a+("&zid="+I);""!=O&&(a+="&xid="+O);if("w"==v){p.__zp_smartpixel_list[v+"_"+r]=!0;var c=t.createElement("iframe");c.setAttribute("scrolling","no");c.frameBorder="0";c.src=a;c.style.cssText="width:1px;height:1px;position:fixed;_position:absolute;left:0px;top:0px;margin:0px;padding:0px;z-index:2147483648";var b=t.createElement("iframe");b.setAttribute("scrolling","no");b.frameBorder="0";b.src="about:blank";b.style.cssText="width:1px;height:1px;position:fixed;_position:absolute;left:0px;top:0px;margin:0px;padding:0px;z-index:2147483648";
setTimeout(function(){try{t.body.insertBefore(c,t.body.firstChild),t.body.insertBefore(b,t.body.firstChild)}catch(a){setTimeout(arguments.callee,13)}},13);setTimeout(function(){try{c.parentNode.removeChild(c),b.parentNode.removeChild(b)}catch(a){}},1E4)}else if("p"==v){var d=new R;d.src=a;p.__zp_smartpixel_list[v+"_"+r]=d}}},ra=function(a){var c="",b="a="+r,b=b+("&zid="+I);""!=J&&(b=b+"&rid="+k(J));""!=O&&(b=b+"&uid="+k(O));if(2==a)c="imp/dasp",""!=l&&(b=b+"&pi="+l),""!=P&&(b=b+"&pt="+P),""!=d&&(b=
b+"&args="+d);else if(3==a){c="imp/dasp3";p.zamplus_tag_params||(p.zamplus_tag_params={});var b=b+"&ext_args=",e;a=p.zamplus_tag_params;a=na||a;C="";if("object"==typeof a)for(e in a)if(a.hasOwnProperty(e)){var g=G(e),f=a[e];if("p_zp_type"==g){if("string"==typeof f||"number"==typeof f)ga=k(G(f))}else if("p_zp_uuid"==g){if("string"==typeof f||"number"==typeof f)ha=k(G(f))}else if("p_zp_conversion"==g){if("string"==typeof f||"number"==typeof f)ia=k(G(f))}else if("p_zp_convinfo"==g){if("string"==typeof f||
"number"==typeof f)ja=k(G(f))}else if("p_zp_prodstype"==g){if("string"==typeof f||"number"==typeof f)fa=k(G(f))}else if("p_zp_prods"==g){if(!("object"!=typeof f||f instanceof Array||la(f)))for(var w in f)""!=f[w]&&(U[w]=f[w])}else if(f instanceof N){for(var m in f)f.hasOwnProperty(m)&&(f[m]=k(G(f[m])));C+=k(g)+"="+f.join(",")+";"}else if("string"==typeof f||"number"==typeof f||"boolean"==typeof f)C+=k(g)+"="+k(G(f))+";"}e=""!=C?C.substring(0,C.length-1):C;b+=k(e)}""!=ga&&(b=b+"&type="+ga);""!=ha&&
(b=b+"&uuid="+ha);""!=ea&&(b=b+"&siteid="+k(ea));b=b+"&vc="+L+"&vt="+V+"&vpc="+K+"&rvt="+Q+"&fr="+T+"&vrt="+M+"&ot="+h;""!=q&&(b=b+"&os="+k(q));""!=E&&(b=b+"&om="+k(E));""!=n&&(b=b+"&oc="+k(n));""!=F&&(b=b+"&ok="+k(F));""!=z&&(b=b+"&oa="+k(z));""!=u&&(b=b+"&u="+k(u));e=p.screen;b=b+"&sc="+k(e.width+"x"+e.height)+"&ch="+k(t.characterSet||t.charset)+"&la="+k(ma.language||ma.userLanguage)+"&ti="+k(t.title)+"&v=3.1.0.15";""!=A&&(b=b+"&ru="+k(A));b=b+"&t=1&r="+Math.random();e=H("//dat.gtags.net/"+c)+"?"+
b;2084<e.length&&W()&&(b=b.replace("&u="+k(u),""),e=(H("//dat.gtags.net/"+c)+"?argserror=true&"+b).substring(0,2084));return[c,e]},sa=function(a,c){try{6<=c.length&&(h=c[0],q=c[1],E=c[2],n=c[3],F=c[4],z=c[5])}catch(d){}var b=[],b=S(u);return"undefined"!=typeof b.zpclkid||"undefined"!=typeof b.utm_source&&"undefined"!=typeof b.utm_campaign&&"undefined"!=typeof b.utm_medium?("undefined"!=typeof b.zpclkid?(E=q="zampda",n=m(b.zpclkid),F=ca(A)[4],z=""):(q=m(b.utm_source),E=m(b.utm_medium),n=m(b.utm_campaign),
F="undefined"!=typeof b.utm_term?m(b.utm_term):ca(A)[4],z="undefined"!=typeof b.utm_content?m(b.utm_content):""),h=1,[!0,[h,q,E,n,F,z].join("|")]):""==A||null==A||"undefined"==A||(new RegExp("^https?://[\\w\\.]*?"+da+"($|/.*|:.*)")).test(A)?a&&0==c.length?(h=4,q=E=n=F=z="",[!0,[h,"||||"].join("|")]):[!1,c.join("|")]:(b=ca(A),2==b[0]||3==b[0]&&a?(h=b[0],q=b[1],F=b[4],E=n=z="",[!0,b.join("|")]):[!1,c.join("|")])},ta=function(a){a=S(u);return"undefined"!=typeof a.zpclkid?a.zpclkid:""},ka=function(a){if(0==
a.length)return!1;for(i in a)if(a.hasOwnProperty(i)&&qa.hasOwnProperty(a[i][0]))qa[a[i][0]](a[i]);return""==r?!1:!0};this.pageView=function(){"undefined"!=typeof _zpq&&(f=ka(_zpq));"undefined"!=typeof _zampq&&(e=ka(_zampq));window.__zpSMConfig=window.__zpSMConfig||[];if(!e&&!f){for(;!e&&0<__zpSMConfig.length;){var h=__zpSMConfig.shift();h&&(e=ka(h.query||[]),na=h.args,Z=h.nosp)}if(!e)return}p.__zp_smartpixel_list||(p.__zp_smartpixel_list={accout_map:{}});0<arguments.length?(A=u,u=arguments[0],u=u.replace(/\t|\n|\r/g,
"")):(u=pa(),A=ba());ua({fun:function(c){I=c;c=new Date;c.setTime(c.getTime()+63072E6);var b=V=L=0,h=Q=0;K=0;var q;q=String(Date.parse(new Date));q=q.substr(0,q.length-3);var F="",E=ta(u),z="",m=oa("__xsptplus"+r).split("#"),n=!1,v=[],C=0;if(!m||5>m.length)n=!0;else{var F=m[2],z=m[4],B=m[0].split("."),v=m[1].split("|");if(5!=B.length||6!=v.length)n=!0;else{L=B[1];b=B[2];h=B[3];K=B[4];try{C=(new Date(parseInt(h+"000"))).getDate()}catch(N){}1800<=q-h&&(n=!0);C!=(new Date(parseInt(q+"000"))).getDate()&&
(n=!0)}}m=[!0,""];0<h&&(M=parseInt((q-h)/86400));n?(L++,T=1,J=E,K=0,b=q,m=sa(n,v)):(m=sa(n,v),p.__zp_smartpixel_list.accout_map&&"undefined"!=typeof p.__zp_smartpixel_list.accout_map[r]&&(m[0]=!1),(n=m[0])?(L++,T=1,J=E,K=0,b=q):(J=F,V=q-b,Q=q-h));h=S(u);h.zpclkid&&h.zpdl&&decodeURIComponent(h.zpdl)&&z!=h.zpclkid&&(z=h.zpclkid,X=decodeURIComponent(h.zpdl));K++;h=r+"."+L+"."+b+"."+q+"."+K+"#"+m[1]+"#"+J+"#"+I+"#"+z;b=da;h=k("__xsptplus"+r)+"="+k(h);c instanceof Date&&(h+="; expires="+c.toGMTString());
h+="; path=/";b&&(h+="; domain="+b);t.cookie=h;p.__zp_smartpixel_list.accout_map||(p.__zp_smartpixel_list.accout_map={});p.__zp_smartpixel_list.accout_map[r]=1;X&&w(X,ta(u));if(!Z){b=b=c="";if(e)b=ra(3);else if(f){c={};if("240"==l)c.ptype="homepage";else if("241"==l)c.ptype="regpage";else if("242"==l)""!=d&&(c.userid=a(d)),c.ptype="regSuccPage";else if("243"==l)""!=d&&(b=d.split(","),3<=b.length&&(c.productId_list=a(b[0]),c.totalPrice=a(b[1]),c.totalNum=a(b[2]))),c.ptype="mycartPage";else if("244"==
l)""!=d&&(b=d.split(","),3<=b.length&&(c.productId_list=a(b[0]),c.totalPrice=a(b[1]),c.totalNum=a(b[2]))),c.ptype="orderInfoPage";else if("245"==l)""!=d&&(b=d.split(","),3<=b.length&&(c.productId_list=a(b[0]),c.totalPrice=a(b[1]),c.totalNum=a(b[2]))),c.ptype="orderInfoPage";else if("246"==l)""!=d&&(b=d.split(","),3<=b.length&&(c.productId=a(b[0]),c.inStock=a(b[1]),c.isWine=a(b[2]))),c.ptype="productPage";else if("247"==l)""!=d&&(b=d.split(","),4<=b.length&&(c.productId_list=a(b[0]),c.catname=a(b[1]),
c.catid=a(b[2]),c.orderby=a(b[3]))),c.ptype="categoryPage";else if("248"==l)""!=d&&(b=d.split(","),3<=b.length&&(c.productId_list=a(b[0]),c.keyword=a(b[1]),c.orderby=a(b[2]))),c.ptype="searchPage";else if("358"==l)""!=d&&(c.cityid=a(d)),c.ptype="homepage";else if("360"==l)""!=d&&(b=d.split(","),2<=b.length&&(c.channelid=a(b[0]),c.categoryid=a(b[1]))),c.ptype="category";else if("361"==l)""!=d&&(c.productid=a(d)),c.ptype="detailpage";else if("362"==l)""!=d&&(c.productid=a(d)),c.ptype="shoppingcart";
else if("457"==l)c.ptype="orderinfo";else if("809"==l)c.ptype="homepage";else if("810"==l)c.ptype="logregpage",""!=d&&(c.action=a(d));else if("811"==l)c.ptype="regSuccPage",""!=d&&(c.userid=a(d));else if("812"==l)c.ptype="searchPage",""!=d&&(b=d.split(","),3<=b.length&&(c.productId_list=a(b[0]),c.keyword=a(b[1]),c.orderby=a(b[2])));else if("813"==l)c.ptype="categoryPage",""!=d&&(b=d.split(","),4<=b.length&&(c.productId_list=a(b[0]),c.catname=a(b[1]),c.catid=a(b[2]),c.orderby=a(b[3])));else if("814"==
l)c.ptype="topicPage",""!=d&&(b=d.split(","),2<=b.length&&(c.productId_list=a(b[0]),c.topicName=a(b[1])));else if("815"==l)c.ptype="productPage",""!=d&&(b=d.split(","),2<=b.length&&(c.productId=a(b[0]),c.inStock=a(b[1])));else if("816"==l)c.ptype="mycartPage",""!=d&&(b=d.split(","),3<=b.length&&(c.productId_list=a(b[0]),c.totalPrice=a(b[1]),c.totalNum=a(b[2])));else if("817"==l)c.ptype="orderInfoPage",""!=d&&(b=d.split(","),3<=b.length&&(c.productId_list=a(b[0]),c.totalPrice=a(b[1]),c.totalNum=a(b[2])));
else if("818"==l)c.ptype="orderSuccPage",""!=d&&(b=d.split(","),3<=b.length&&(c.productId_list=a(b[0]),c.totalPrice=a(b[1]),c.totalNum=a(b[2])));else if("752"==l)c.ptype="homepage";else if("753"==l)c.ptype="regpage";else if("754"==l)c.ptype="regSuccPage";else if("755"==l)c.ptype="familysalesPage";else if("756"==l)c.ptype="chanelPage",""!=d&&(c.chanelName=a(d));else if("757"==l)c.ptype="searchPage",""!=d&&(b=d.split(","),3<=b.length&&(c.productId_list=a(b[0]),c.keyword=a(b[1]),c.orderby=a(b[2])));
else if("758"==l)c.ptype="categoryPage",""!=d&&(b=d.split(","),4<=b.length&&(c.productId_list=a(b[0]),c.catname=a(b[1]),c.brand=a(b[2]),c.orderby=a(b[3])));else if("759"==l)c.ptype="productPage",""!=d&&(b=d.split(","),4<=b.length&&(c.productId=a(b[0]),c.inStock=a(b[1]),c.inventoryDiv=a(b[2]),c.flashBuyTime=a(b[3])));else if("760"==l)c.ptype="mycartPage",""!=d&&(b=d.split(","),3<=b.length&&(c.productId_list=a(b[0]),c.totalPrice=a(b[1]),c.totalNum=a(b[2])));else if("761"==l)c.ptype="orderInfoPage",
""!=d&&(b=d.split(","),3<=b.length&&(c.productId_list=a(b[0]),c.totalPrice=a(b[1]),c.totalNum=a(b[2])));else if("762"==l)c.ptype="orderSuccPage",""!=d&&(b=d.split(","),3<=b.length&&(c.productId_list=a(b[0]),c.totalPrice=a(b[1]),c.totalNum=a(b[2])));else if("854"==l)c.ptype="homepage";else if("855"==l)c.ptype="logregpage",""!=d&&(c.action=a(d));else if("856"==l)c.ptype="regSuccPage",""!=d&&(c.userid=a(d));else if("857"==l)c.ptype="specialPage",""!=d&&(b=d.split(","),3<=b.length&&(c.productId_list=
a(b[0]),c.keyword=a(b[1]),c.orderby=a(b[2])));else if("858"==l)c.ptype="promotionsPage",""!=d&&(b=d.split(","),2<=b.length&&(c.productId_list=a(b[0]),c.orderby=a(b[1])));else if("859"==l)c.ptype="topicPage",""!=d&&(b=d.split(","),2<=b.length&&(c.productId_list=a(b[0]),c.topicName=a(b[1])));else if("860"==l)c.ptype="productPage",""!=d&&(b=d.split(","),2<=b.length&&(c.productId=a(b[0]),c.inStock=a(b[1])));else if("861"==l)c.ptype="mycartPage",""!=d&&(b=d.split(","),3<=b.length&&(c.productId_list=a(b[0]),
c.totalPrice=a(b[1]),c.totalNum=a(b[2])));else if("862"==l)c.ptype="orderInfoPage",""!=d&&(b=d.split(","),3<=b.length&&(c.productId_list=a(b[0]),c.totalPrice=a(b[1]),c.totalNum=a(b[2])));else if("863"==l)c.ptype="orderSuccPage",""!=d&&(b=d.split(","),3<=b.length&&(c.productId_list=a(b[0]),c.totalPrice=a(b[1]),c.totalNum=a(b[2])));else if(c.pagetype=P,""!=d)for(b=d.split(","),h=0;h<b.length;h++)c[P+"_k"+(h+1)]=a(b[h]).split(",");p.zamplus_tag_params=c;b=ra(3)}c=b[0];b=b[1];g=new R;p.__zp_smartpixel_list[c]||
(p.__zp_smartpixel_list[c]=[]);p.__zp_smartpixel_list[c].push(g);g.src=b;T=0}aa();""!=ia&&(b="a="+r+"&c="+ia+"&zid="+I+"&allow=0&type=23",""!=J&&(b=b+"&i="+k(J)),""!=ja&&(b=b+"&info="+ja),""!=u&&(b=b+"&u="+k(u)),""!=A&&(b=b+"&ru="+k(A)),b+="&r="+Math.random(),c=H("//ut.gtags.net/imp/conv")+"?"+b,2084<c.length&&W()&&(b=b.replace("&u="+k(u),""),c=(H("//ut.gtags.net/imp/conv")+"?argserror=true&"+b).substring(0,2084)),b=new R,p.__zp_smartpixel_list["//ut.gtags.net/imp/conv_"+r]=b,b.src=c);if(""!=fa&&
!la(U)){c="a="+r+"&t="+fa;for(var D in U)c+="&"+D+"="+k(G(U[D]));c+="&_="+(Math.random()+"").substr(2);D=H("//ut.gtags.net/imp/material")+"?"+c;2084<D.length&&W()||(c=new R,p.__zp_smartpixel_list["//ut.gtags.net/imp/material"]=c,c.src=D)}},a:r,zid:oa("__xsptplus"+r).split("#")[3]});f&&(_zpq=[]);e&&(_zampq=[])}}).pageView();window.__zampBroadcast||(window.__zampBroadcast=function(){try{var a=function(e,f){f=f||"opener.top";m[f]||k.push(e);for(var h=0,g;h<e.frames.length&&(g=e.frames[h]);h++)a(g,f+
".frames["+h+"]")},e=function(a,g){g=g||"opener.top";if(a==opener)f=g;else for(var h=0,k;h<a.frames.length&&(k=a.frames[h]);h++)e(k,g+".frames["+h+"]")},f="",g=opener.top,k=[],m={};e(g);(function(a,e){var f=arguments.callee;k.push(a);m[e]=1;a.parent!=a&&f(a.parent,e.replace(/\.[^\.]+$/i,""))})(opener,f);a(g,"");(function(){if(k[0]){var a=k.shift();try{a.postMessage({token:"catchLanding",landing:document.location.href,sourceUrl:ba(),sourceFramePath:f},"*")}catch(e){}setTimeout(arguments.callee,1)}})()}catch(Q){}},
window.__zampBroadcast());(function(){function a(){k||(k=1,clearInterval(g),g=setInterval(function(){null!=I&&null!=Y&&(clearInterval(g),(new Image).src=H("//dat.gtags.net/imp/hm")+"?zid="+I+"&a="+Y+"&u="+encodeURIComponent(document.location)+"&ru="+encodeURIComponent(ba())+"&_="+Math.random())},50))}function e(){try{var e=function(e){try{var g=e.accelerationIncludingGravity;h=g.x;_y=g.y;_z=g.z;if(Math.abs(h-_lastX)>f||Math.abs(_y-_lastY)>f||Math.abs(_z-_lastZ)>f)m=1,a();_lastX=h;_lastY=_y;_lastZ=
_z}catch(k){}};if(!m&&(top.addEventListener||top.removeEventListener)){top.DeviceMotionEvent&&(top.addEventListener("devicemotion",e,!1),top.addEventListener("devicemotion",e,!1),top.addEventListener("devicemotion",e,!1));var f=.04,h=_y=_z=_lastX=_lastY=_lastZ=0}}catch(g){}}function f(e){function f(n){clearTimeout(m);m=setTimeout(function(){for(var m=0;m<g.length-1;m++){var n=g[m],p=g[m+1];if(null==n||null==p)return;if(n[0]!=p[0]||n[1]!=p[1]){m=e;n=f;m.removeEventListener?m.removeEventListener("mousemove",
n,!1):m.detachEvent?m.detachEvent("onmousemove",n):m.onmousemove=null;a();return}}g=[];k=null},30);document.all?(x=n.clientX,y=n.clientY):(x=n.pageX,y=n.pageY);k&&g.push([x-k[0],y-k[1]]);k=[x,y]}var g=[],k,m;aa(e,"mousemove",f)}if(!Z){var g,k=0,m=0;e();f(document.body)}})()})();
